openapi: 3.1.0
info:
  title: Article API
  description: Article 관리 API
  version: 1.0.0
servers:
  - url: 'https://api.example.com'
    description: Production server
  - url: 'http://localhost:8080'
    description: Local development server

paths:
  /v1/articles/{articleId}:
    get:
      summary: Article 조회
      description: articleId로 Article을 조회합니다.
      operationId: readArticle
      tags:
        - Article
      parameters:
        - name: articleId
          in: path
          required: true
          description: Article ID
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleResponse'
        '404':
          description: Article을 찾을 수 없음
          
    put:
      summary: Article 수정
      description: articleId로 Article을 수정합니다.
      operationId: updateArticle
      tags:
        - Article
      parameters:
        - name: articleId
          in: path
          required: true
          description: Article ID
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArticleUpdateRequest'
      responses:
        '200':
          description: 수정 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleResponse'
        '404':
          description: Article을 찾을 수 없음
          
    delete:
      summary: Article 삭제
      description: articleId로 Article을 삭제합니다.
      operationId: deleteArticle
      tags:
        - Article
      parameters:
        - name: articleId
          in: path
          required: true
          description: Article ID
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: 삭제 성공
        '404':
          description: Article을 찾을 수 없음

components:
  schemas:
    ArticleResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Article ID
        title:
          type: string
          description: 제목
        content:
          type: string
          description: 내용
        createdAt:
          type: string
          format: date-time
          description: 생성일시
        updatedAt:
          type: string
          format: date-time
          description: 수정일시
      required:
        - id
        - title
        - content
        - boardId
        - writerId
        - createdAt
        - updatedAt
        
    ArticleUpdateRequest:
      type: object
      properties:
        title:
          type: string
          description: 제목
        content:
          type: string
          description: 내용
      required:
        - title
        - content
